### PR TITLE
`python_function_line_count` updated

### PR DESCRIPTION
**Pull request by ShrutiKatpara**
Hi, I have updated the necessary changes required to resolve [issue #7 ](https://github.com/democritus-project/d8s-python/issues/7)

Can you please check if everything's alright and merge the PR.

Thanks :)

### CODE REVIEW

**Review by fhightower — APPROVED** [review]
Thanks @ShrutiKatpara ! This looks good to me. Do you have any input @riyalalwani19?

**Comment by fhightower** [comment]
@ShrutiKatpara : Before I can merge this PR, you'll have to sync the `7-add-line-count-func` branch of your fork with the `main` branch of this repo to resolve conflicts. This is necessary because I made some updates to this library while you were working on your PR.

This should be pretty easy to do and I've included a list of commands below that will sync the `7-add-line-count-func` branch of your fork with the `main` branch of this repo.

Run this from the root directory of the `7-add-line-count-func` branch of your fork:

```shell
git remote add upstream https://github.com/democritus-project/d8s-python.git  # see https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork
git fetch upstream  # pull updates from 'upstream' (in this case, https://github.com/democritus-project/d8s-python.git)
git merge upstream/main  # merge the updates from the 'main' branch of 'upstream'

# at this point, the `7-add-line-count-func` branch of your fork will be update so that it contains...
# the updates I've made to this library while you were working on the PR and...
# the great updates you've made

git push  # this will push your changes to the `7-add-line-count-func` branch and this PR
```

As always, let me know if you have any questions and I'm happy to help!

**Comment by ShrutiKatpara** [comment]
Hi @fhightower , I ran your commands on my root directory of the `7-add-line-count-func` branch of my fork. 
I got such message for `git push` : 
image

Shall I run the command that is recommended ? 

Thanks again for all your help :)

**Comment by fhightower** [comment]
> Hi @fhightower , I ran your commands on my root directory of the `7-add-line-count-func` branch of my fork.
> I got such message for `git push` :
> image
> 
> Shall I run the command that is recommended ?
> 
> Thanks again for all your help :)

Hi @ShrutiKatpara: no problem; I'm happy to help. Yes, try running that command (`git push --set-upstream origin 7-add-line-count-func`) and that should do the trick.

**Comment by ShrutiKatpara** [comment]
Yeah, I have completed running the command

> > Hi @fhightower , I ran your commands on my root directory of the `7-add-line-count-func` branch of my fork.
> > I got such message for `git push` :
> > image
> > Shall I run the command that is recommended ?
> > Thanks again for all your help :)
> 
> Hi @ShrutiKatpara: no problem; I'm happy to help. Yes, try running that command (`git push --set-upstream origin 7-add-line-count-func`) and that should do the trick.

Hey, @fhightower. I have completed running the commands. Can you please check it.

**Comment by fhightower** [comment]
Perfect, looks good to me @ShrutiKatpara! I'll merge this in 🚀 

Thank you for contributing 🎉  ! There are some other I plan to keep creating issues on which I would like some help, so feel free to check back!

I plan to keep creating issues on which I would like some help, so feel free to check back in this repo or other repos in the [Democritus Project](https://github.com/democritus-project)!

**Comment by ShrutiKatpara** [comment]
> Perfect, looks good to me @ShrutiKatpara! I'll merge this in 🚀
> 
> Thank you for contributing 🎉 !
> 
> I plan to keep creating issues on which I would like some help, so feel free to check back in this repo or other repos in the [Democritus Project](https://github.com/democritus-project).

Hey @fhightower. Thanks for merging it! It was great working with you. I got to learn so many new things. Thanks to all your cooperation. I would be happy to contribute more on this work. Will surely check back again. Thanks :)

**Pull request merged**
